[package]
name = "ruin"
version = "0.1.1"
edition = "2021"

[dependencies]
home = "0.5.5"
image = "0.24.7"
os-release = "0.1.0"
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }
