[package]
name = "bain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
image = "0.23.14"
photon-rs = "0.3.2"
wallpaper = "3.2.0"
