[package]
name = "ruin"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Battery indicator as wallpaper for most unix systems"
repository = "https://github.com/unixpariah/ruin.git"

[dependencies]
image = "0.24.7"
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }
wallpaper = "3.2.0"
