[package]
name = "ruin"
version = "1.2.6"
edition = "2021"
license = "MIT"
description = "Battery indicator as wallpaper"
repository = "https://github.com/unixpariah/ruin.git"

[dependencies]
image = "0.24.7"
reqwest = "0.11.22"
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.31"
tokio = { version = "1.34.0", features = ["full"] }
wallpaper = "3.2.0"
wlrs = "0.x.x"
