[package]
name = "ruin"
version = "1.1.2"
edition = "2021"
license = "MIT"
description = "Battery indicator as wallpaper for most unix systems"
repository = "https://github.com/unixpariah/ruin.git"

[dependencies]
wlrs = { path = "../wlrs" }
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.31"
wallpaper = "3.2.0"
image = "0.24.7"
reqwest = "0.11.22"
